import { ASTRO, FURNIRO, INTERIOR, MEDICAL, TVISTA_HOLIDAYS, WEDDING, WILDORA, WORKS_1 } from "@/constants/images";

const projectDetails = [
    {
        title: "Wildora Travel Website",
        description: "A modern travel and tour booking website with nature theme.",
        image: WILDORA,
        link: "#",
        project: "Next.js",
    },
    {
        title: "Ecoland Residence",
        description: "Sustainable living platform showcasing eco-friendly housing.",
        image: WEDDING,
        link: "#",
        project: "Next.js",
    },
    {
        title: "Foodies Hub",
        description: "Restaurant ordering and food delivery platform.",
        image: TVISTA_HOLIDAYS,
        link: "#",
        project: "Next.js",
    },
    {
        title: "TechNova Portfolio",
        description: "Personal portfolio website for developers and designers.",
        image: MEDICAL,
        link: "#",
        project: "Next.js",
    },
    {
        title: "EventSphere",
        description: "Event management and ticket booking application.",
        image: INTERIOR,
        link: "#",
        project: "Next.js",
    },
    {
        title: "FitLife Pro",
        description: "Fitness coaching and workout tracking platform.",
        image: FURNIRO,
        link: "#",
        project: "Next.js",
    },
    {
        title: "EduNext Academy",
        description: "E-learning platform with courses and video lessons.",
        image: ASTRO,
        link: "#",
        project: "Next.js",
    },
    {
        title: "ShopEase",
        description: "E-commerce platform for fashion and lifestyle products.",
        image: WORKS_1,
        link: "#",
        project: "Next.js",
    },
    {
        title: "CryptoPulse",
        description: "Cryptocurrency tracking and analytics dashboard.",
        image: WORKS_1,
        link: "#",
        project: "Next.js",
    },
    {
        title: "HealthCare Connect",
        description: "Doctor appointment booking and telehealth service.",
        image: WORKS_1,
        link: "#",
        project: "Next.js",
    },

    // 🔹 React Native (5 projects)
    {
        title: "TravelMate App",
        description: "Mobile app for trip planning and travel guides.",
        image: WORKS_1,
        link: "#",
        project: "React Native",
    },
    {
        title: "FitTrack",
        description: "Fitness and health tracking mobile application.",
        image: WORKS_1,
        link: "#",
        project: "React Native",
    },
    {
        title: "FoodieExpress",
        description: "Food delivery mobile app with real-time tracking.",
        image: WORKS_1,
        link: "#",
        project: "React Native",
    },
    {
        title: "BookNest",
        description: "Mobile app for reading and sharing e-books.",
        image: WORKS_1,
        link: "#",
        project: "React Native",
    },
    {
        title: "TaskFlow",
        description: "Task management and productivity app.",
        image: WORKS_1,
        link: "#",
        project: "React Native",
    },

    // 🔹 Webflow (5 projects)
    {
        title: "Creative Studio",
        description: "Creative agency portfolio built with Webflow.",
        image: WORKS_1,
        link: "#",
        project: "Webflow",
    },
    {
        title: "Urban Real Estate",
        description: "Property listing and real estate business website.",
        image: WORKS_1,
        link: "#",
        project: "Webflow",
    },
    {
        title: "GreenFarm",
        description: "Organic farm and agricultural business website.",
        image: WORKS_1,
        link: "#",
        project: "Webflow",
    },
    {
        title: "StartupX",
        description: "Landing page for a modern startup.",
        image: WORKS_1,
        link: "#",
        project: "Webflow",
    },
    {
        title: "ArtVibe",
        description: "Artist and gallery showcase website.",
        image: WORKS_1,
        link: "#",
        project: "Webflow",
    },

    // 🔹 HTML (10 projects)
    {
        title: "Portfolio Classic",
        description: "Clean and responsive personal portfolio website.",
        image: INTERIOR,
        link: "#",
        project: "HTML",
    },
    {
        title: "Restaurant Delight",
        description: "Restaurant landing page with menu and booking.",
        image: WORKS_1,
        link: "#",
        project: "HTML",
    },
    {
        title: "Travel Explorer Blog",
        description: "Travel blogging website with image galleries.",
        image: WORKS_1,
        link: "#",
        project: "HTML",
    },
    {
        title: "Fitness Landing Page",
        description: "Landing page for a fitness trainer.",
        image: WORKS_1,
        link: "#",
        project: "HTML",
    },
    {
        title: "EduLearn",
        description: "Simple educational website template.",
        image: WORKS_1,
        link: "#",
        project: "HTML",
    },
    {
        title: "Fashion Trendz",
        description: "Fashion e-commerce landing page.",
        image: WORKS_1,
        link: "#",
        project: "HTML",
    },
    {
        title: "EventPro",
        description: "Event registration and schedule site.",
        image: WORKS_1,
        link: "#",
        project: "HTML",
    },
    {
        title: "TechBlog",
        description: "Responsive blog for tech articles.",
        image: WORKS_1,
        link: "#",
        project: "HTML",
    },
    {
        title: "Startup Launch",
        description: "One-page startup product launch website.",
        image: WORKS_1,
        link: "#",
        project: "HTML",
    },
    {
        title: "Cafe Mocha",
        description: "Coffee shop website with online menu.",
        image: WORKS_1,
        link: "#",
        project: "HTML",
    },
    // 🔹 WordPress (10 projects)
    {
        title: "TravelGo Blog",
        description: "Travel blogging site with booking integrations.",
        image: WORKS_1,
        link: "#",
        project: "WordPress",
    },
    {
        title: "FoodiePress",
        description: "Restaurant website with menu and online reservation.",
        image: WORKS_1,
        link: "#",
        project: "WordPress",
    },
    {
        title: "EduPress Academy",
        description: "E-learning site with courses and student dashboards.",
        image: WORKS_1,
        link: "#",
        project: "WordPress",
    },
    {
        title: "Wellness Spa",
        description: "Health and spa service booking website.",
        image: WORKS_1,
        link: "#",
        project: "WordPress",
    },
    {
        title: "News360",
        description: "News and magazine publishing website.",
        image: WORKS_1,
        link: "#",
        project: "WordPress",
    },
    {
        title: "BizConsult",
        description: "Corporate website for consulting services.",
        image: WORKS_1,
        link: "#",
        project: "WordPress",
    },
    {
        title: "ArtGallery WP",
        description: "Portfolio and gallery showcase for artists.",
        image: WORKS_1,
        link: "#",
        project: "WordPress",
    },
    {
        title: "ShopifyClone",
        description: "E-commerce store with WooCommerce integration.",
        image: WORKS_1,
        link: "#",
        project: "WordPress",
    },
    {
        title: "Eventify WP",
        description: "Event booking and ticketing platform.",
        image: WORKS_1,
        link: "#",
        project: "WordPress",
    },
    {
        title: "RealEstate Pro",
        description: "Real estate property listing and booking site.",
        image: WORKS_1,
        link: "#",
        project: "WordPress",
    },

];

export default projectDetails;
